<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Umbraco.Cms.Persistence.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cogworks.Umbraco.FormsGuard\Cogworks.Umbraco.FormsGuard.csproj" />
    <ProjectReference Include="..\Cogworks.Umbraco.FormsGuard.UmbracoAI\Cogworks.Umbraco.FormsGuard.UmbracoAI.csproj" />
    <ProjectReference Include="..\Cogworks.Umbraco.FormsGuard.Evaluation\Cogworks.Umbraco.FormsGuard.Evaluation.csproj" />
  </ItemGroup>

</Project>
