// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ApproveData, ApproveErrors, ApproveResponses, ConfirmSpamData, ConfirmSpamErrors, ConfirmSpamResponses, CreateRuleData, CreateRuleErrors, CreateRuleResponses, DeleteRuleData, DeleteRuleErrors, DeleteRuleResponses, GetAuditData, GetAuditErrors, GetAuditResponses, GetDecisionsData, GetDecisionsErrors, GetDecisionsResponses, GetFormsData, GetFormsErrors, GetFormSettingsData, GetFormSettingsErrors, GetFormSettingsResponses, GetFormsResponses, GetLogFormsData, GetLogFormsErrors, GetLogFormsResponses, GetReviewQueueData, GetReviewQueueErrors, GetReviewQueueResponses, GetRulesData, GetRulesErrors, GetRulesResponses, RestoreData, RestoreErrors, RestoreResponses, SaveFormSettingsData, SaveFormSettingsErrors, SaveFormSettingsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class DecisionsService {
    public static getAudit<ThrowOnError extends boolean = false>(options?: Options<GetAuditData, ThrowOnError>): RequestResult<GetAuditResponses, GetAuditErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetAuditResponses, GetAuditErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/formsguard/api/v1/audit',
            ...options
        });
    }
    
    public static getDecisions<ThrowOnError extends boolean = false>(options?: Options<GetDecisionsData, ThrowOnError>): RequestResult<GetDecisionsResponses, GetDecisionsErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetDecisionsResponses, GetDecisionsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/formsguard/api/v1/decisions',
            ...options
        });
    }
    
    public static getLogForms<ThrowOnError extends boolean = false>(options?: Options<GetLogFormsData, ThrowOnError>): RequestResult<GetLogFormsResponses, GetLogFormsErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetLogFormsResponses, GetLogFormsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/formsguard/api/v1/decisions/forms',
            ...options
        });
    }
}

export class ReviewService {
    public static getReviewQueue<ThrowOnError extends boolean = false>(options?: Options<GetReviewQueueData, ThrowOnError>): RequestResult<GetReviewQueueResponses, GetReviewQueueErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetReviewQueueResponses, GetReviewQueueErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/formsguard/api/v1/review',
            ...options
        });
    }
    
    public static approve<ThrowOnError extends boolean = false>(options: Options<ApproveData, ThrowOnError>): RequestResult<ApproveResponses, ApproveErrors, ThrowOnError> {
        return (options.client ?? client).post<ApproveResponses, ApproveErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/formsguard/api/v1/review/{recordId}/approve',
            ...options
        });
    }
    
    public static confirmSpam<ThrowOnError extends boolean = false>(options: Options<ConfirmSpamData, ThrowOnError>): RequestResult<ConfirmSpamResponses, ConfirmSpamErrors, ThrowOnError> {
        return (options.client ?? client).post<ConfirmSpamResponses, ConfirmSpamErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/formsguard/api/v1/review/{recordId}/confirm-spam',
            ...options
        });
    }
    
    public static restore<ThrowOnError extends boolean = false>(options: Options<RestoreData, ThrowOnError>): RequestResult<RestoreResponses, RestoreErrors, ThrowOnError> {
        return (options.client ?? client).post<RestoreResponses, RestoreErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/formsguard/api/v1/review/{recordId}/restore',
            ...options
        });
    }
}

export class SettingsService {
    public static getForms<ThrowOnError extends boolean = false>(options?: Options<GetFormsData, ThrowOnError>): RequestResult<GetFormsResponses, GetFormsErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetFormsResponses, GetFormsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/formsguard/api/v1/settings/forms',
            ...options
        });
    }
    
    public static getFormSettings<ThrowOnError extends boolean = false>(options: Options<GetFormSettingsData, ThrowOnError>): RequestResult<GetFormSettingsResponses, GetFormSettingsErrors, ThrowOnError> {
        return (options.client ?? client).get<GetFormSettingsResponses, GetFormSettingsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/formsguard/api/v1/settings/forms/{formId}',
            ...options
        });
    }
    
    public static saveFormSettings<ThrowOnError extends boolean = false>(options: Options<SaveFormSettingsData, ThrowOnError>): RequestResult<SaveFormSettingsResponses, SaveFormSettingsErrors, ThrowOnError> {
        return (options.client ?? client).put<SaveFormSettingsResponses, SaveFormSettingsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/formsguard/api/v1/settings/forms/{formId}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static getRules<ThrowOnError extends boolean = false>(options: Options<GetRulesData, ThrowOnError>): RequestResult<GetRulesResponses, GetRulesErrors, ThrowOnError> {
        return (options.client ?? client).get<GetRulesResponses, GetRulesErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/formsguard/api/v1/settings/forms/{formId}/rules',
            ...options
        });
    }
    
    public static createRule<ThrowOnError extends boolean = false>(options: Options<CreateRuleData, ThrowOnError>): RequestResult<CreateRuleResponses, CreateRuleErrors, ThrowOnError> {
        return (options.client ?? client).post<CreateRuleResponses, CreateRuleErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/formsguard/api/v1/settings/forms/{formId}/rules',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static deleteRule<ThrowOnError extends boolean = false>(options: Options<DeleteRuleData, ThrowOnError>): RequestResult<DeleteRuleResponses, DeleteRuleErrors, ThrowOnError> {
        return (options.client ?? client).delete<DeleteRuleResponses, DeleteRuleErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/formsguard/api/v1/settings/forms/{formId}/rules/{ruleId}',
            ...options
        });
    }
}
