// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44326' | (string & {});
};

export type AuditListItem = {
    id: number;
    recordId?: string | null;
    formId?: string | null;
    action: string;
    actor?: string | null;
    actorName?: string | null;
    detail?: string | null;
    createdUtc: string;
};

export type AuditPagedResult = {
    total: number;
    items: Array<AuditListItem>;
};

export type CreateRuleRequest = {
    ruleType?: string | null;
    pattern?: string | null;
};

export type DecisionListItem = {
    id: number;
    recordId: string;
    formId: string;
    status: string;
    source?: string | null;
    ruleHit?: string | null;
    provider?: string | null;
    modelVersion?: string | null;
    probabilities?: {
        [key: string]: number;
    } | null;
    attempts: number;
    reviewer?: string | null;
    reviewerName?: string | null;
    createdUtc: string;
    updatedUtc: string;
};

export type DecisionPagedResult = {
    total: number;
    approvedNotCheckedTotal: number;
    items: Array<DecisionListItem>;
};

export type DecisionStatus = 'Pending' | 'Approved' | 'ApprovedNotChecked' | 'Quarantined' | 'Review';

export type FormFieldModel = {
    id: string;
    caption?: string | null;
    alias?: string | null;
    excluded: boolean;
    looksLikeEmail: boolean;
};

export type FormReadinessModel = {
    manualApprovalOff: boolean;
    submitWorkflowNames: Array<string>;
};

export type FormSettingsModel = {
    organisation?: string | null;
    allowedFieldIds?: Array<string> | null;
    sendEmailDomain?: boolean | null;
    questions?: Array<QuestionModel> | null;
    thresholds?: ThresholdsModel | null;
    failurePolicy?: string | null;
    emailFieldId?: string | null;
};

export type FormSettingsResponse = {
    formId: string;
    formName: string;
    guarded: boolean;
    settings: FormSettingsModel;
    fields: Array<FormFieldModel>;
    readiness: FormReadinessModel;
};

export type FormSummary = {
    id: string;
    name: string;
    guarded: boolean;
    readiness?: FormReadinessModel | null;
};

export type LogFormOption = {
    id: string;
    name: string;
};

export type QuestionModel = {
    key?: string | null;
    text?: string | null;
    role?: string | null;
    enabled?: boolean | null;
    trueCriteria?: string | null;
    falseCriteria?: string | null;
};

export type ReviewActionResponse = {
    outcome: string;
    status?: string | null;
};

export type ReviewQueueField = {
    caption?: string | null;
    value?: string | null;
};

export type ReviewQueueItem = {
    decision: DecisionListItem;
    formName?: string | null;
    recordMissing: boolean;
    fields: Array<ReviewQueueField>;
};

export type ReviewQueuePagedResult = {
    total: number;
    items: Array<ReviewQueueItem>;
    canEditEntries: boolean;
};

export type RuleModel = {
    id: number;
    ruleType: string;
    pattern: string;
    createdUtc: string;
};

export type SaveFormSettingsRequest = {
    guarded?: boolean | null;
    settings?: FormSettingsModel | null;
};

export type ThresholdsModel = {
    quarantineSpamMin?: number | null;
    approveSpamMax?: number | null;
    approveGenuineMin?: number | null;
};

export type ValidationErrorsResponse = {
    errors: Array<string>;
};

export type GetAuditData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
        formId?: string;
        fromUtc?: string;
        toUtc?: string;
    };
    url: '/umbraco/formsguard/api/v1/audit';
};

export type GetAuditErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetAuditResponses = {
    /**
     * OK
     */
    200: AuditPagedResult;
};

export type GetAuditResponse = GetAuditResponses[keyof GetAuditResponses];

export type GetDecisionsData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
        formId?: string;
        status?: DecisionStatus;
        fromUtc?: string;
        toUtc?: string;
    };
    url: '/umbraco/formsguard/api/v1/decisions';
};

export type GetDecisionsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetDecisionsResponses = {
    /**
     * OK
     */
    200: DecisionPagedResult;
};

export type GetDecisionsResponse = GetDecisionsResponses[keyof GetDecisionsResponses];

export type GetLogFormsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/formsguard/api/v1/decisions/forms';
};

export type GetLogFormsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetLogFormsResponses = {
    /**
     * OK
     */
    200: Array<LogFormOption>;
};

export type GetLogFormsResponse = GetLogFormsResponses[keyof GetLogFormsResponses];

export type GetReviewQueueData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/formsguard/api/v1/review';
};

export type GetReviewQueueErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetReviewQueueResponses = {
    /**
     * OK
     */
    200: ReviewQueuePagedResult;
};

export type GetReviewQueueResponse = GetReviewQueueResponses[keyof GetReviewQueueResponses];

export type ApproveData = {
    body?: never;
    path: {
        recordId: string;
    };
    query?: never;
    url: '/umbraco/formsguard/api/v1/review/{recordId}/approve';
};

export type ApproveErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: ReviewActionResponse;
    /**
     * Internal Server Error
     */
    500: ReviewActionResponse;
};

export type ApproveError = ApproveErrors[keyof ApproveErrors];

export type ApproveResponses = {
    /**
     * OK
     */
    200: ReviewActionResponse;
};

export type ApproveResponse = ApproveResponses[keyof ApproveResponses];

export type ConfirmSpamData = {
    body?: never;
    path: {
        recordId: string;
    };
    query?: never;
    url: '/umbraco/formsguard/api/v1/review/{recordId}/confirm-spam';
};

export type ConfirmSpamErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: ReviewActionResponse;
    /**
     * Internal Server Error
     */
    500: ReviewActionResponse;
};

export type ConfirmSpamError = ConfirmSpamErrors[keyof ConfirmSpamErrors];

export type ConfirmSpamResponses = {
    /**
     * OK
     */
    200: ReviewActionResponse;
};

export type ConfirmSpamResponse = ConfirmSpamResponses[keyof ConfirmSpamResponses];

export type RestoreData = {
    body?: never;
    path: {
        recordId: string;
    };
    query?: never;
    url: '/umbraco/formsguard/api/v1/review/{recordId}/restore';
};

export type RestoreErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: ReviewActionResponse;
    /**
     * Internal Server Error
     */
    500: ReviewActionResponse;
};

export type RestoreError = RestoreErrors[keyof RestoreErrors];

export type RestoreResponses = {
    /**
     * OK
     */
    200: ReviewActionResponse;
};

export type RestoreResponse = RestoreResponses[keyof RestoreResponses];

export type GetFormsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/formsguard/api/v1/settings/forms';
};

export type GetFormsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetFormsResponses = {
    /**
     * OK
     */
    200: Array<FormSummary>;
};

export type GetFormsResponse = GetFormsResponses[keyof GetFormsResponses];

export type GetFormSettingsData = {
    body?: never;
    path: {
        formId: string;
    };
    query?: never;
    url: '/umbraco/formsguard/api/v1/settings/forms/{formId}';
};

export type GetFormSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetFormSettingsResponses = {
    /**
     * OK
     */
    200: FormSettingsResponse;
};

export type GetFormSettingsResponse = GetFormSettingsResponses[keyof GetFormSettingsResponses];

export type SaveFormSettingsData = {
    body?: SaveFormSettingsRequest;
    path: {
        formId: string;
    };
    query?: never;
    url: '/umbraco/formsguard/api/v1/settings/forms/{formId}';
};

export type SaveFormSettingsErrors = {
    /**
     * Bad Request
     */
    400: ValidationErrorsResponse;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type SaveFormSettingsError = SaveFormSettingsErrors[keyof SaveFormSettingsErrors];

export type SaveFormSettingsResponses = {
    /**
     * OK
     */
    200: FormSettingsResponse;
};

export type SaveFormSettingsResponse = SaveFormSettingsResponses[keyof SaveFormSettingsResponses];

export type GetRulesData = {
    body?: never;
    path: {
        formId: string;
    };
    query?: never;
    url: '/umbraco/formsguard/api/v1/settings/forms/{formId}/rules';
};

export type GetRulesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetRulesResponses = {
    /**
     * OK
     */
    200: Array<RuleModel>;
};

export type GetRulesResponse = GetRulesResponses[keyof GetRulesResponses];

export type CreateRuleData = {
    body?: CreateRuleRequest;
    path: {
        formId: string;
    };
    query?: never;
    url: '/umbraco/formsguard/api/v1/settings/forms/{formId}/rules';
};

export type CreateRuleErrors = {
    /**
     * Bad Request
     */
    400: ValidationErrorsResponse;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type CreateRuleError = CreateRuleErrors[keyof CreateRuleErrors];

export type CreateRuleResponses = {
    /**
     * OK
     */
    200: RuleModel;
};

export type CreateRuleResponse = CreateRuleResponses[keyof CreateRuleResponses];

export type DeleteRuleData = {
    body?: never;
    path: {
        formId: string;
        ruleId: number;
    };
    query?: never;
    url: '/umbraco/formsguard/api/v1/settings/forms/{formId}/rules/{ruleId}';
};

export type DeleteRuleErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteRuleResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRuleResponse = DeleteRuleResponses[keyof DeleteRuleResponses];
